# Generated by Django 4.0.5 on 2022-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
